// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodigoComun.Entities
{
    public partial class Articulo
    {
        public Articulo()
        {
            Stocks = new HashSet<Stock>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public decimal? MinimoStock { get; set; }
        public string Proveedor { get; set; }
        public decimal? Precio { get; set; }
        public string Codigo { get; set; }

        public virtual ICollection<Stock> Stocks { get; set; }
    }
}